// <auto-generated />
using System;
using Gestion_Bibliotheque.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Bibliotheque.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528160255_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Bibliotheque.Models.Abonnement", b =>
                {
                    b.Property<int>("id_abonnement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_abonnement"));

                    b.Property<DateTime>("date_debutabonnement")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_finabonnement")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_membres")
                        .HasColumnType("int");

                    b.Property<string>("type_abonnement")
                        .HasColumnType("longtext");

                    b.HasKey("id_abonnement");

                    b.HasIndex("id_membres");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Models.Emprunt", b =>
                {
                    b.Property<int>("id_emprunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_emprunt"));

                    b.Property<DateTime>("date_emprunt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("date_retoureffective")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_retourprevue")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_livres")
                        .HasColumnType("int");

                    b.Property<int>("id_membres")
                        .HasColumnType("int");

                    b.Property<string>("statut")
                        .HasColumnType("longtext");

                    b.HasKey("id_emprunt");

                    b.HasIndex("id_livres");

                    b.HasIndex("id_membres");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Models.Livre", b =>
                {
                    b.Property<int>("id_livres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_livres"));

                    b.Property<string>("auteur")
                        .HasColumnType("longtext");

                    b.Property<string>("categorie")
                        .HasColumnType("longtext");

                    b.Property<bool>("disponibilite")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("quantite")
                        .HasColumnType("int");

                    b.Property<string>("titre")
                        .HasColumnType("longtext");

                    b.HasKey("id_livres");

                    b.ToTable("livres");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Models.Membre", b =>
                {
                    b.Property<int>("id_membres")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_membres"));

                    b.Property<string>("adresse_membres")
                        .HasColumnType("longtext");

                    b.Property<string>("email_membres")
                        .HasColumnType("longtext");

                    b.Property<string>("nom_membres")
                        .HasColumnType("longtext");

                    b.Property<string>("prenom_membres")
                        .HasColumnType("longtext");

                    b.Property<string>("tel_membres")
                        .HasColumnType("longtext");

                    b.HasKey("id_membres");

                    b.ToTable("membres");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Models.Penalite", b =>
                {
                    b.Property<int>("id_penalite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_penalite"));

                    b.Property<DateTime>("date_penalite")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_emprunt")
                        .HasColumnType("int");

                    b.Property<decimal>("montant_penalite")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("raison_penalite")
                        .HasColumnType("longtext");

                    b.HasKey("id_penalite");

                    b.HasIndex("id_emprunt");

                    b.ToTable("Penalites");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Models.Abonnement", b =>
                {
                    b.HasOne("Gestion_Bibliotheque.Models.Membre", "Membre")
                        .WithMany()
                        .HasForeignKey("id_membres")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Models.Emprunt", b =>
                {
                    b.HasOne("Gestion_Bibliotheque.Models.Livre", "Livre")
                        .WithMany()
                        .HasForeignKey("id_livres")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Bibliotheque.Models.Membre", "Membre")
                        .WithMany()
                        .HasForeignKey("id_membres")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("Gestion_Bibliotheque.Models.Penalite", b =>
                {
                    b.HasOne("Gestion_Bibliotheque.Models.Emprunt", "Emprunt")
                        .WithMany()
                        .HasForeignKey("id_emprunt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprunt");
                });
#pragma warning restore 612, 618
        }
    }
}
